import { Rubik } from "next/font/google";
import "./globals.css";
// components of the layout
import Navbar from "./components/Navbar";

const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
    
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
       <Navbar/>
        {children}
      </body>
    </html>
  );
}
