import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Rubik({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Rubik.className}>
       <Navbar/>
        {children}
      </body>
    </html>
  );
}
